# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _raypy
else:
    import _raypy

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


TYPE_LIST = _raypy.TYPE_LIST
TYPE_BOOL = _raypy.TYPE_BOOL
TYPE_BYTE = _raypy.TYPE_BYTE
TYPE_I64 = _raypy.TYPE_I64
TYPE_F64 = _raypy.TYPE_F64
TYPE_SYMBOL = _raypy.TYPE_SYMBOL
TYPE_TIMESTAMP = _raypy.TYPE_TIMESTAMP
TYPE_GUID = _raypy.TYPE_GUID
TYPE_CHAR = _raypy.TYPE_CHAR
TYPE_ENUM = _raypy.TYPE_ENUM
TYPE_ANYMAP = _raypy.TYPE_ANYMAP
TYPE_FILTERMAP = _raypy.TYPE_FILTERMAP
TYPE_GROUPMAP = _raypy.TYPE_GROUPMAP
TYPE_TABLE = _raypy.TYPE_TABLE
TYPE_DICT = _raypy.TYPE_DICT
TYPE_LAMBDA = _raypy.TYPE_LAMBDA
TYPE_UNARY = _raypy.TYPE_UNARY
TYPE_BINARY = _raypy.TYPE_BINARY
TYPE_VARY = _raypy.TYPE_VARY
TYPE_ERROR = _raypy.TYPE_ERROR
OK = _raypy.OK
ERR_INIT = _raypy.ERR_INIT
ERR_PARSE = _raypy.ERR_PARSE
ERR_EVAL = _raypy.ERR_EVAL
ERR_FORMAT = _raypy.ERR_FORMAT
ERR_TYPE = _raypy.ERR_TYPE
ERR_LENGTH = _raypy.ERR_LENGTH
ERR_ARITY = _raypy.ERR_ARITY
ERR_INDEX = _raypy.ERR_INDEX
ERR_HEAP = _raypy.ERR_HEAP
ERR_IO = _raypy.ERR_IO
ERR_SYS = _raypy.ERR_SYS
ERR_NOT_FOUND = _raypy.ERR_NOT_FOUND
ERR_NOT_EXIST = _raypy.ERR_NOT_EXIST
ERR_NOT_IMPLEMENTED = _raypy.ERR_NOT_IMPLEMENTED
ERR_NOT_SUPPORTED = _raypy.ERR_NOT_SUPPORTED
ERR_STACK_OVERFLOW = _raypy.ERR_STACK_OVERFLOW
ERR_RAISE = _raypy.ERR_RAISE
ERR_UNKNOWN = _raypy.ERR_UNKNOWN
class guid_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    buf = property(_raypy.guid_t_buf_get, _raypy.guid_t_buf_set)

    def __init__(self):
        _raypy.guid_t_swiginit(self, _raypy.new_guid_t())
    __swig_destroy__ = _raypy.delete_guid_t

# Register guid_t in _raypy:
_raypy.guid_t_swigregister(guid_t)

class obj_t(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    mmod = property(_raypy.obj_t_mmod_get, _raypy.obj_t_mmod_set)
    refc = property(_raypy.obj_t_refc_get, _raypy.obj_t_refc_set)
    type = property(_raypy.obj_t_type_get, _raypy.obj_t_type_set)
    attrs = property(_raypy.obj_t_attrs_get, _raypy.obj_t_attrs_set)
    rc = property(_raypy.obj_t_rc_get, _raypy.obj_t_rc_set)
    u8 = property(_raypy.obj_t_u8_get, _raypy.obj_t_u8_set)
    vchar = property(_raypy.obj_t_vchar_get, _raypy.obj_t_vchar_set)
    i64 = property(_raypy.obj_t_i64_get, _raypy.obj_t_i64_set)
    f64 = property(_raypy.obj_t_f64_get, _raypy.obj_t_f64_set)
    obj = property(_raypy.obj_t_obj_get, _raypy.obj_t_obj_set)
    len = property(_raypy.obj_t_len_get, _raypy.obj_t_len_set)
    arr = property(_raypy.obj_t_arr_get, _raypy.obj_t_arr_set)

    def __init__(self):
        _raypy.obj_t_swiginit(self, _raypy.new_obj_t())
    __swig_destroy__ = _raypy.delete_obj_t

# Register obj_t in _raypy:
_raypy.obj_t_swigregister(obj_t)


def version():
    return _raypy.version()

def null(type):
    return _raypy.null(type)

def atom(type):
    return _raypy.atom(type)

def list(len):
    return _raypy.list(len)

def vn_list(*args):
    return _raypy.vn_list(*args)

def vector(type, len):
    return _raypy.vector(type, len)

def vn_symbol(*args):
    return _raypy.vn_symbol(*args)

def u8(val):
    return _raypy.u8(val)

def i64(val):
    return _raypy.i64(val)

def f64(val):
    return _raypy.f64(val)

def symbol(ptr):
    return _raypy.symbol(ptr)

def symboli64(id):
    return _raypy.symboli64(id)

def timestamp(val):
    return _raypy.timestamp(val)

def guid(buf):
    return _raypy.guid(buf)

def vchar(c):
    return _raypy.vchar(c)

def string(len):
    return _raypy.string(len)

def venum(sym, vec):
    return _raypy.venum(sym, vec)

def anymap(sym, vec):
    return _raypy.anymap(sym, vec)

def table(keys, vals):
    return _raypy.table(keys, vals)

def dict(keys, vals):
    return _raypy.dict(keys, vals)

def clone(obj):
    return _raypy.clone(obj)

def cow(obj):
    return _raypy.cow(obj)

def rc(obj):
    return _raypy.rc(obj)

def raise_error(*args):
    return _raypy.raise_error(*args)

def drop(obj):
    return _raypy.drop(obj)

def is_null(obj):
    return _raypy.is_null(obj)

def typename(type):
    return _raypy.typename(type)

def push_raw(obj, val):
    return _raypy.push_raw(obj, val)

def push_obj(obj, val):
    return _raypy.push_obj(obj, val)

def push_sym(obj, str):
    return _raypy.push_sym(obj, str)

def pop_obj(obj):
    return _raypy.pop_obj(obj)

def ins_raw(obj, idx, val):
    return _raypy.ins_raw(obj, idx, val)

def ins_obj(obj, idx, val):
    return _raypy.ins_obj(obj, idx, val)

def ins_sym(obj, idx, str):
    return _raypy.ins_sym(obj, idx, str)

def at_idx(obj, idx):
    return _raypy.at_idx(obj, idx)

def at_ids(obj, ids, len):
    return _raypy.at_ids(obj, ids, len)

def at_obj(obj, idx):
    return _raypy.at_obj(obj, idx)

def symtostr(id):
    return _raypy.symtostr(id)

def zero_obj(obj):
    return _raypy.zero_obj(obj)

def set_idx(obj, idx, val):
    return _raypy.set_idx(obj, idx, val)

def set_obj(obj, idx, val):
    return _raypy.set_obj(obj, idx, val)

def resize(obj, len):
    return _raypy.resize(obj, len)

def find_raw(obj, val):
    return _raypy.find_raw(obj, val)

def find_obj(obj, val):
    return _raypy.find_obj(obj, val)

def find_sym(obj, str):
    return _raypy.find_sym(obj, str)

def _as(type, obj):
    return _raypy._as(type, obj)

def objcmp(a, b):
    return _raypy.objcmp(a, b)

def ser(obj):
    return _raypy.ser(obj)

def de(buf):
    return _raypy.de(buf)

def parse_str(fd, str, file):
    return _raypy.parse_str(fd, str, file)

def eval_str(fd, str, file):
    return _raypy.eval_str(fd, str, file)

def eval_obj(fd, obj):
    return _raypy.eval_obj(fd, obj)

def try_obj(obj, catch):
    return _raypy.try_obj(obj, catch)


